language: python

python:
  - "3.6"

sudo: true

before_install:
  - wget https://github.com/ethereum/solidity/releases/download/v0.5.0/solc-static-linux
  - chmod +x solc-static-linux
  - sudo cp solc-static-linux /usr/bin/solc

install:
  - pip install -r requirements_dev.txt

script:
  - pytest
